general:
  # input_dir_prefix: /mercury/data3/asahasra/Phase2L1tAlgoStudies/asahasra-flat-table-analyser/puppiIsoData
  input_dir_prefix: ./Phase2EGPuppiIso_151Xv1_Ntuples
  output_dir: ./OutHistoFiles
  tree_name: Events

samples:
  DYToLL_M50_PU0:
    input_file_pattern: DYToLL_M50_PU0/FP/v151Xv1/perfNano_*.root
    type: 'dytoll'

  DYToLL_M50_PU200:
    input_file_pattern: DYToLL_M50_PU200/FP/v151Xv1/perfNano_*.root
    type: 'dytoll'

  MinBias_PU200:
    input_file_pattern: MinBias_PU200/FP/v151Xv1/perfNano_*.root
    type: 'qcd'

  # QCD_Pt20To30:
  #   input_file_pattern: QCD_Pt20To30/FP/v142Xv1/perfNano_*.root
  #   type: 'qcd'

  # QCD_Pt30To50:
  #   input_file_pattern: QCD_Pt30To50/FP/v142Xv1/perfNano_*.root
  #   type: 'qcd'

  # QCD_Pt50To80:
  #   input_file_pattern: QCD_Pt50To80/FP/v142Xv1/perfNano_*.root
  #   type: 'qcd'

  # QCD_Pt80To120:
  #   input_file_pattern: QCD_Pt80To120/FP/v142Xv1/perfNano_*.root
  #   type: 'qcd'

  # QCD_Pt120To170:
  #   input_file_pattern: QCD_Pt120To170/FP/v142Xv1/perfNano_*.root
  #   type: 'qcd'
