general:
  hist_folder: ./OutHistoFiles/
  samples:
    MinBias: hists_MinBias.root
    DY_noPU: hists_DY_noPU.root
    DY_PU200: hists_DY_PU200.root

# AN plots for STEP 1_0_0
compareGen_DYM50_PromptAndEtaSel:
  norm_scheme:
    method: 'hist_integral'
  hist_tag:
    DY_noPU: base_GenEl_DYP
    DY_PU200: base_GenEl_DYP

# AN plots for STEP 1_0_0
compareGenSel_DYM50:
  type: same_sample_different_collection
  norm_scheme:
    method: 'hist_integral'
  ftags: ['DY_noPU', 'DY_PU200']
  hist_tag:
    prefix:
      'all': GenEl
      'status = 0': GenEl_GENST0
      'status = 1': GenEl_GENST1
      'status = 2': GenEl_GENST2
      'status = 2, |#eta| < 2.5': GenEl_DYP
    collection: ['base_{tag}']

# AN plots for STEP 1_2_0
compareGenDYP_DYM50_MinBias:
  norm_scheme:
    method: 'summed_components'
    norm_config: {refsample: DY_PU200} 
  hist_tag:
    MinBias: tke1_[TkEleL2, L1PuppiCandsEl, L1PuppiCandsMu, L1PuppiCandsCh, L1PuppiCandsNh, L1PuppiCandsPh]
    DY_noPU: genDYP_[TkEleL2, L1PuppiCandsEl, L1PuppiCandsMu, L1PuppiCandsCh, L1PuppiCandsNh, L1PuppiCandsPh]
    DY_PU200: genDYP_[TkEleL2, L1PuppiCandsEl, L1PuppiCandsMu, L1PuppiCandsCh, L1PuppiCandsNh, L1PuppiCandsPh]

# AN plots for STEP 2_0_0
compareERegion_DYM50_GenMatching:
  type: same_sample_different_collection
  norm_scheme:
    method: hist_integral
  ftags: ['DY_noPU', 'DY_PU200']
  hist_tag:
    prefix:
      EE: EE
      EB: EB
    collection: ['DYP{tag}_GenEl_DYP_TkEleL2_{tag}',
                 'DYP{tag}_GenEl_DYP_MCH_TkEleL2_{tag}_MCH']

# AN plots for STEP 2_1_0
compareTkEl_inER_DYM50_GenMatched:
  type: same_sample_different_collection
  norm_scheme:
    method: default_no_norm
  ftags: ['DY_noPU', 'DY_PU200']
  hist_tag:
    prefix:
      All: ''
      EB: _MCH
    collection: ['DYPEB_TkEleL2_EB{tag}', 'DYPEE_TkEleL2_EE{tag}']



# AN plots for STEP 1_2_0 and STEP 3_1_0
# TkEl_Puppi_Duplicate_GenDYPDYM50_MB:
#   hist_tag:
#     MinBias: >
#       el[
#       EB_L1PuppiCandsEl, EB_L1PuppiCandsPh, EB_L1PuppiCandsCh, EB_L1PuppiCandsNh, EB_L1PuppiCandsMu,
#       EM_L1PuppiCandsEl, EM_L1PuppiCandsPh, EM_L1PuppiCandsCh, EM_L1PuppiCandsNh, EM_L1PuppiCandsMu,
#       EE_L1PuppiCandsEl, EE_L1PuppiCandsPh, EE_L1PuppiCandsCh, EE_L1PuppiCandsNh, EE_L1PuppiCandsMu,
#       EF_L1PuppiCandsEl, EF_L1PuppiCandsPh, EF_L1PuppiCandsCh, EF_L1PuppiCandsNh, EF_L1PuppiCandsMu]
#     DY_noPU: >
#       genDYPTkElMCH[
#       EB_L1PuppiCandsEl, EB_L1PuppiCandsPh, EB_L1PuppiCandsCh, EB_L1PuppiCandsNh, EB_L1PuppiCandsMu,
#       EM_L1PuppiCandsEl, EM_L1PuppiCandsPh, EM_L1PuppiCandsCh, EM_L1PuppiCandsNh, EM_L1PuppiCandsMu,
#       EE_L1PuppiCandsEl, EE_L1PuppiCandsPh, EE_L1PuppiCandsCh, EE_L1PuppiCandsNh, EE_L1PuppiCandsMu,
#       EF_L1PuppiCandsEl, EF_L1PuppiCandsPh, EF_L1PuppiCandsCh, EF_L1PuppiCandsNh, EF_L1PuppiCandsMu]
#     DY_PU200: >
#       genDYPTkElMCH[
#       EB_L1PuppiCandsEl, EB_L1PuppiCandsPh, EB_L1PuppiCandsCh, EB_L1PuppiCandsNh, EB_L1PuppiCandsMu,
#       EM_L1PuppiCandsEl, EM_L1PuppiCandsPh, EM_L1PuppiCandsCh, EM_L1PuppiCandsNh, EM_L1PuppiCandsMu,
#       EE_L1PuppiCandsEl, EE_L1PuppiCandsPh, EE_L1PuppiCandsCh, EE_L1PuppiCandsNh, EE_L1PuppiCandsMu,
#       EF_L1PuppiCandsEl, EF_L1PuppiCandsPh, EF_L1PuppiCandsCh, EF_L1PuppiCandsNh, EF_L1PuppiCandsMu]

# TkEl_Puppi_NoDuplicate_GenDYPDYM50_MB:
#   hist_tag:
#     MinBias: >
#       el[
#       EB_L1PuppiCandsNoTkElDEl, EB_L1PuppiCandsNoTkElDPh, EB_L1PuppiCandsNoTkElDCh, EB_L1PuppiCandsNoTkElDNh, EB_L1PuppiCandsNoTkElDMu,
#       EM_L1PuppiCandsNoTkElDEl, EM_L1PuppiCandsNoTkElDPh, EM_L1PuppiCandsNoTkElDCh, EM_L1PuppiCandsNoTkElDNh, EM_L1PuppiCandsNoTkElDMu,
#       EE_L1PuppiCandsNoTkElDEl, EE_L1PuppiCandsNoTkElDPh, EE_L1PuppiCandsNoTkElDCh, EE_L1PuppiCandsNoTkElDNh, EE_L1PuppiCandsNoTkElDMu,
#       EF_L1PuppiCandsNoTkElDEl, EF_L1PuppiCandsNoTkElDPh, EF_L1PuppiCandsNoTkElDCh, EF_L1PuppiCandsNoTkElDNh, EF_L1PuppiCandsNoTkElDMu]
#     DY_noPU: >
#       genDYPTkElMCH[
#       EB_L1PuppiCandsNoTkElDEl, EB_L1PuppiCandsNoTkElDPh, EB_L1PuppiCandsNoTkElDCh, EB_L1PuppiCandsNoTkElDNh, EB_L1PuppiCandsNoTkElDMu,
#       EM_L1PuppiCandsNoTkElDEl, EM_L1PuppiCandsNoTkElDPh, EM_L1PuppiCandsNoTkElDCh, EM_L1PuppiCandsNoTkElDNh, EM_L1PuppiCandsNoTkElDMu,
#       EE_L1PuppiCandsNoTkElDEl, EE_L1PuppiCandsNoTkElDPh, EE_L1PuppiCandsNoTkElDCh, EE_L1PuppiCandsNoTkElDNh, EE_L1PuppiCandsNoTkElDMu,
#       EF_L1PuppiCandsNoTkElDEl, EF_L1PuppiCandsNoTkElDPh, EF_L1PuppiCandsNoTkElDCh, EF_L1PuppiCandsNoTkElDNh, EF_L1PuppiCandsNoTkElDMu]
#     DY_PU200: >
#       genDYPTkElMCH[
#       EB_L1PuppiCandsNoTkElDEl, EB_L1PuppiCandsNoTkElDPh, EB_L1PuppiCandsNoTkElDCh, EB_L1PuppiCandsNoTkElDNh, EB_L1PuppiCandsNoTkElDMu,
#       EM_L1PuppiCandsNoTkElDEl, EM_L1PuppiCandsNoTkElDPh, EM_L1PuppiCandsNoTkElDCh, EM_L1PuppiCandsNoTkElDNh, EM_L1PuppiCandsNoTkElDMu,
#       EE_L1PuppiCandsNoTkElDEl, EE_L1PuppiCandsNoTkElDPh, EE_L1PuppiCandsNoTkElDCh, EE_L1PuppiCandsNoTkElDNh, EE_L1PuppiCandsNoTkElDMu,
#       EF_L1PuppiCandsNoTkElDEl, EF_L1PuppiCandsNoTkElDPh, EF_L1PuppiCandsNoTkElDCh, EF_L1PuppiCandsNoTkElDNh, EF_L1PuppiCandsNoTkElDMu]

# compareDuplicateRemoval:
#   type: same_sample_different_collection
#   ftags: ['DY_noPU', 'DY_PU200']
#   hist_tag:
#     prefix:
#       dR < 0.5: PuppiCandsInTkEl
#       0.005 < dR < 0.5: PuppiCandsNoTkElD
#       All: PuppiCands
#     collection: [
#       'genDYPTkElMCHEB_L1{tag}El', 'genDYPTkElMCHEB_L1{tag}Ph', 'genDYPTkElMCHEB_L1{tag}Ch', 'genDYPTkElMCHEB_L1{tag}Nh', 'genDYPTkElMCHEB_L1{tag}Mu',
#       'genDYPTkElMCHEM_L1{tag}El', 'genDYPTkElMCHEM_L1{tag}Ph', 'genDYPTkElMCHEM_L1{tag}Ch', 'genDYPTkElMCHEM_L1{tag}Nh', 'genDYPTkElMCHEM_L1{tag}Mu',
#       'genDYPTkElMCHEE_L1{tag}El', 'genDYPTkElMCHEE_L1{tag}Ph', 'genDYPTkElMCHEE_L1{tag}Ch', 'genDYPTkElMCHEE_L1{tag}Nh', 'genDYPTkElMCHEE_L1{tag}Mu',
#       'genDYPTkElMCHEF_L1{tag}El', 'genDYPTkElMCHEF_L1{tag}Ph', 'genDYPTkElMCHEF_L1{tag}Ch', 'genDYPTkElMCHEF_L1{tag}Nh', 'genDYPTkElMCHEF_L1{tag}Mu']

# # AN plots for STEP 3_0_0
# compare_DYM50GENMCH_MinBias_EB:
#   hist_tag:
#     MinBias: >
#       elEB_[TkEleL2_EB,
#       L1PuppiCandsEl_0p0dR0p1, L1PuppiCandsMu_0p0dR0p1, L1PuppiCandsCh_0p0dR0p1, L1PuppiCandsNh_0p0dR0p1, L1PuppiCandsPh_0p0dR0p1,
#       L1PuppiCandsEl_0p1dR0p2, L1PuppiCandsMu_0p1dR0p2, L1PuppiCandsCh_0p1dR0p2, L1PuppiCandsNh_0p1dR0p2, L1PuppiCandsPh_0p1dR0p2,
#       L1PuppiCandsEl_0p2dR0p3, L1PuppiCandsMu_0p2dR0p3, L1PuppiCandsCh_0p2dR0p3, L1PuppiCandsNh_0p2dR0p3, L1PuppiCandsPh_0p2dR0p3,
#       L1PuppiCandsEl_0p3dR0p4, L1PuppiCandsMu_0p3dR0p4, L1PuppiCandsCh_0p3dR0p4, L1PuppiCandsNh_0p3dR0p4, L1PuppiCandsPh_0p3dR0p4,
#       L1PuppiCandsEl_0p4dR10, L1PuppiCandsMu_0p4dR10, L1PuppiCandsCh_0p4dR10, L1PuppiCandsNh_0p4dR10, L1PuppiCandsPh_0p4dR10]
#     DY_noPU: >
#       genDYPTkElMCHEB_[TkEleL2_EB_MCH,
#       L1PuppiCandsEl_0p0dR0p1, L1PuppiCandsMu_0p0dR0p1, L1PuppiCandsCh_0p0dR0p1, L1PuppiCandsNh_0p0dR0p1, L1PuppiCandsPh_0p0dR0p1,
#       L1PuppiCandsEl_0p1dR0p2, L1PuppiCandsMu_0p1dR0p2, L1PuppiCandsCh_0p1dR0p2, L1PuppiCandsNh_0p1dR0p2, L1PuppiCandsPh_0p1dR0p2,
#       L1PuppiCandsEl_0p2dR0p3, L1PuppiCandsMu_0p2dR0p3, L1PuppiCandsCh_0p2dR0p3, L1PuppiCandsNh_0p2dR0p3, L1PuppiCandsPh_0p2dR0p3,
#       L1PuppiCandsEl_0p3dR0p4, L1PuppiCandsMu_0p3dR0p4, L1PuppiCandsCh_0p3dR0p4, L1PuppiCandsNh_0p3dR0p4, L1PuppiCandsPh_0p3dR0p4,
#       L1PuppiCandsEl_0p4dR10, L1PuppiCandsMu_0p4dR10, L1PuppiCandsCh_0p4dR10, L1PuppiCandsNh_0p4dR10, L1PuppiCandsPh_0p4dR10]
#     DY_PU200: >
#       genDYPTkElMCHEB_[TkEleL2_EB_MCH,
#       L1PuppiCandsEl_0p0dR0p1, L1PuppiCandsMu_0p0dR0p1, L1PuppiCandsCh_0p0dR0p1, L1PuppiCandsNh_0p0dR0p1, L1PuppiCandsPh_0p0dR0p1,
#       L1PuppiCandsEl_0p1dR0p2, L1PuppiCandsMu_0p1dR0p2, L1PuppiCandsCh_0p1dR0p2, L1PuppiCandsNh_0p1dR0p2, L1PuppiCandsPh_0p1dR0p2,
#       L1PuppiCandsEl_0p2dR0p3, L1PuppiCandsMu_0p2dR0p3, L1PuppiCandsCh_0p2dR0p3, L1PuppiCandsNh_0p2dR0p3, L1PuppiCandsPh_0p2dR0p3,
#       L1PuppiCandsEl_0p3dR0p4, L1PuppiCandsMu_0p3dR0p4, L1PuppiCandsCh_0p3dR0p4, L1PuppiCandsNh_0p3dR0p4, L1PuppiCandsPh_0p3dR0p4,
#       L1PuppiCandsEl_0p4dR10, L1PuppiCandsMu_0p4dR10, L1PuppiCandsCh_0p4dR10, L1PuppiCandsNh_0p4dR10, L1PuppiCandsPh_0p4dR10]

# compare_DYM50GENMCH_MinBias_EE:
#   hist_tag:
#     MinBias: >
#       elEE_[TkEleL2_EE,
#       L1PuppiCandsEl_0p0dR0p1, L1PuppiCandsMu_0p0dR0p1, L1PuppiCandsCh_0p0dR0p1, L1PuppiCandsNh_0p0dR0p1, L1PuppiCandsPh_0p0dR0p1,
#       L1PuppiCandsEl_0p1dR0p2, L1PuppiCandsMu_0p1dR0p2, L1PuppiCandsCh_0p1dR0p2, L1PuppiCandsNh_0p1dR0p2, L1PuppiCandsPh_0p1dR0p2,
#       L1PuppiCandsEl_0p2dR0p3, L1PuppiCandsMu_0p2dR0p3, L1PuppiCandsCh_0p2dR0p3, L1PuppiCandsNh_0p2dR0p3, L1PuppiCandsPh_0p2dR0p3,
#       L1PuppiCandsEl_0p3dR0p4, L1PuppiCandsMu_0p3dR0p4, L1PuppiCandsCh_0p3dR0p4, L1PuppiCandsNh_0p3dR0p4, L1PuppiCandsPh_0p3dR0p4,
#       L1PuppiCandsEl_0p4dR10, L1PuppiCandsMu_0p4dR10, L1PuppiCandsCh_0p4dR10, L1PuppiCandsNh_0p4dR10, L1PuppiCandsPh_0p4dR10]
#     DY_noPU: >
#       genDYPTkElMCHEE_[TkEleL2_EE_MCH,
#       L1PuppiCandsEl_0p0dR0p1, L1PuppiCandsMu_0p0dR0p1, L1PuppiCandsCh_0p0dR0p1, L1PuppiCandsNh_0p0dR0p1, L1PuppiCandsPh_0p0dR0p1,
#       L1PuppiCandsEl_0p1dR0p2, L1PuppiCandsMu_0p1dR0p2, L1PuppiCandsCh_0p1dR0p2, L1PuppiCandsNh_0p1dR0p2, L1PuppiCandsPh_0p1dR0p2,
#       L1PuppiCandsEl_0p2dR0p3, L1PuppiCandsMu_0p2dR0p3, L1PuppiCandsCh_0p2dR0p3, L1PuppiCandsNh_0p2dR0p3, L1PuppiCandsPh_0p2dR0p3,
#       L1PuppiCandsEl_0p3dR0p4, L1PuppiCandsMu_0p3dR0p4, L1PuppiCandsCh_0p3dR0p4, L1PuppiCandsNh_0p3dR0p4, L1PuppiCandsPh_0p3dR0p4,
#       L1PuppiCandsEl_0p4dR10, L1PuppiCandsMu_0p4dR10, L1PuppiCandsCh_0p4dR10, L1PuppiCandsNh_0p4dR10, L1PuppiCandsPh_0p4dR10]
#     DY_PU200: >
#       genDYPTkElMCHEE_[TkEleL2_EE_MCH,
#       L1PuppiCandsEl_0p0dR0p1, L1PuppiCandsMu_0p0dR0p1, L1PuppiCandsCh_0p0dR0p1, L1PuppiCandsNh_0p0dR0p1, L1PuppiCandsPh_0p0dR0p1,
#       L1PuppiCandsEl_0p1dR0p2, L1PuppiCandsMu_0p1dR0p2, L1PuppiCandsCh_0p1dR0p2, L1PuppiCandsNh_0p1dR0p2, L1PuppiCandsPh_0p1dR0p2,
#       L1PuppiCandsEl_0p2dR0p3, L1PuppiCandsMu_0p2dR0p3, L1PuppiCandsCh_0p2dR0p3, L1PuppiCandsNh_0p2dR0p3, L1PuppiCandsPh_0p2dR0p3,
#       L1PuppiCandsEl_0p3dR0p4, L1PuppiCandsMu_0p3dR0p4, L1PuppiCandsCh_0p3dR0p4, L1PuppiCandsNh_0p3dR0p4, L1PuppiCandsPh_0p3dR0p4,
#       L1PuppiCandsEl_0p4dR10, L1PuppiCandsMu_0p4dR10, L1PuppiCandsCh_0p4dR10, L1PuppiCandsNh_0p4dR10, L1PuppiCandsPh_0p4dR10]
